name: Medical Devices
favicon: null
layout_spectrum: 0.4013
typography_spectrum: 0.9115629473235458
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.49336219672113657
  lightness: 0.30022848257794976
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
